services:
  backend:
    build: .
    container_name: youtube-summarizer-backend
    ports:
      - "5000:5000"
    volumes:
      - ./.env:/app/.env
    environment:
      - PORT=5000
    command: gunicorn --bind 0.0.0.0:5000 --timeout 600 run:app
    restart: unless-stopped
    network_mode: bridge
